services:
  server:
    build:
      context: .
    ports:
      - 8081:8081
    volumes:
      - .:/app  # Mount the current directory to the container
    environment:
      - SPRING_DATA_MONGODB_URI=
      - SPRING_DATA_MONGODB_DATABASE=photovault
      - SPRING_DATA_MONGODB_SSL_ENABLED=true
    # restart: always

